from flash_abb import pretrained
import torch

flabb = pretrained(device='cuda')

seq1 = [
    'EVQLLESGGEVKKPGASVKVSCRASGYTFRNYGLTWVRQAPGQGLEWMGWISAYNGNTNYAQKFQGRVTLTTDTSTSTAYMELRSLRSDDTAVYFCARDVPGHGAAFMDVWGTGTTVTVSS', # Heavy chain
    'DIQLTQSPLSLPVTLGQPASISCRSSQSLEASDTNIYLSWFQQRPGQSPRRLIYKISNRDSGVPDRFSGSGSGTHFTLRISRVEADDVAVYYCMQGTHWPPAFGQGTKVDIK' # Light chain
]
seq2 = [
    'EVQLLESGGEVKKPGASVKVSCRASGYTFRNYGLTWVRQAPGQGLEWMGWISAYNGNTNYAQKFQGRVTLTTDTSTSTAYMELRSLRSDDTAVYFCARDVPGHGAAFMDVWGTGTTVTVS', # Heavy chain
    'DIQLTQSPLSLPVTLGQPASISCRSSQSLEASDTNIYLSWFQQRPGQSPRRLIYKISNRDSGVPDRFSGSGSGTHFTLRISRVEADDVAVYYCMQGTHWPPAFGQGTKVDIK' # Light chain
]
seqs = [seq1, seq2]
seqs = [f'{seq[0]}|{seq[1]}' for seq in seqs]
names = ['test1', 'test2']

with torch.no_grad():
    result = flabb(seqs)

# Coords returns a tensor of the predicted coordinates
print(result.coords.shape)

# Save predictions as PDB files
result.to_pdbs(names, pdb_dir='sample_preds')
